org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=die_nbt
mod_name=Die, NBT!
mod_license=MIT
mod_version=1.0.0-1.20.1
mod_group_id=com.gencal.die_nbt
mod_authors=Gencal
mod_description=When you die, NBT tags on items from your inventory get cleared. Per-Item and Per-Mod Configurable!
